### ISSUE TITLE
Requirement file not found while pip installing

### ISSUE THREAD

**Issue by efertitta** [pyscf/mpi4pyscf#21]
While pip installing I get the following error.
I ran the following command: pip3 install --user mpi4pyscf
It seems someone else flagged a similar issue in June but was not resolved yet? Thank you

Collecting mpi4pyscf
  Using cached https://files.pythonhosted.org/packages/05/7b/227c77a3c5ef88ff9ef61058287ef898e16eca0eeb198decc50274d11f55/mpi4pyscf-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ytn46qjt/mpi4pyscf/setup.py", line 15, in <module>
        with open(os.path.join(topdir, 'requirements.txt'), 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-ytn46qjt/mpi4pyscf/requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ytn46qjt/mpi4pyscf/

**Comment by sunqm** [comment]
For the moment you can try installing the package from source code
```
pip install git+https://github.com/pyscf/mpi4pyscf
```
