### ISSUE TITLE
Parallel-mol_dft example not working

### ISSUE THREAD

**Issue by moritzgubler** [pyscf/mpi4pyscf#23]
Hi @sunqm 
Im am trying to use the mpi4pyscf plugin for pyscf and have just installed both packages with pip. The version of pyscf is 2.1.1 and the version of mpi4pyscf is 0.3.1. 
When running the example 04-parallel_mol_dft.py I get the following error: 
Traceback (most recent call last):
 File "/home/moritz/.local/lib/python3.10/site-packages/mpi4pyscf/__init__.py", line 31, in <module>
    mpi.pool.wait()
  File "/home/moritz/.local/lib/python3.10/site-packages/mpi4pyscf/tools/mpi_pool.py", line 111, in wait
    ans = self.function(*task)  # task = worker_args
  File "/home/moritz/.local/lib/python3.10/site-packages/mpi4pyscf/tools/mpi.py", line 584, in _distribute_call
    return fn(dev, *args, **kwargs)
  File "/home/moritz/.local/lib/python3.10/site-packages/mpi4pyscf/dft/rks.py", line 43, in get_veff
    _setup_grids_(mf, dm)
  File "/home/moritz/.local/lib/python3.10/site-packages/mpi4pyscf/dft/rks.py", line 114, in _setup_grids_
    if abs(n-mol.nelectron) < rks.NELEC_ERROR_TOL*n:
AttributeError: module 'pyscf.dft.rks' has no attribute 'NELEC_ERROR_TOL'
Do you have an idea what could cause this?  The error is triggered by line 24: "mf.run()". Is it possible that the version of pyscf and mpi4pyscf are not compatible? If so which versions are compatible?

Thanks a lot for your help.

**Comment by BallisticBill** [comment]
Any updates on this issues?
